### PR TITLE
execute wrapper script from desktop file

### PR DESCRIPTION
**Pull request by Bleuzen**

### CODE REVIEW

**Comment by hfiguiere** [comment]
my approach is to actually rename the binary and name the wrapper script as the binary was.

**Comment by Bleuzen** [comment]
changed it already:
https://github.com/flathub/studio.kx.carla/commit/f486de91b0080ba38a17f7f9b4d077c63e3829fd

**Comment by hfiguiere** [comment]
actually since carla is a script, I patch the script :-) it's what I do for ardour. (lmms is a binary)

**Comment by Bleuzen** [comment]
@hfiguiere I know but intentionally try to avoid patching upstream files if possible because they may change at any time.
Always making our own wrapper script is much more robust.
Because what if with next release, the apps script will look completely different or even become a binary? Your patching method will break.
While if always using a wrapper script, it will still work.
Thats why I would prefer a wrapper script even for Ardour.

**Comment by hfiguiere** [comment]
it's your call you are the mainainer.

**Comment by Bleuzen** [comment]
Sure thanks for the hint, but will keep it as is :)

**Pull request merged**
